ログインページを作成
ok-os-job-change-team/tetsuya-frontend-bootcamp pull request #5
Opened 2024-01-06 00:51 UTC by kawabuchi-tetsuya

ログインページのみ作成
![Screenshot 2024-01-06 9 50 31](https://github.com/ok-os-job-change-team/tetsuya-frontend-bootcamp/assets/95535099/519a3f91-79a8-4574-884b-232493868cd8)

2024-01-06 03:48 UTC, ochi-sho-private-study reviewed
- アクセシビリティの観点から、pxを使っている部分は、remを使うように修正した方が良さそう！
  - Reference: https://coliss.com/articles/build-websites/operation/css/about-pixels-and-accessibility.html
- フォームに、emailやpasswordといったラベルをつけた方がよさそう。

2024-01-06 04:12 UTC, ochi-sho-private-study requested changes
@kawabuchi-tetsuya 
コメントしました〜！

2024-01-06 04:12 UTC, kakeru-one commented on form_login/css/style.css
ファイル名は`login_form/index.css`でいいと思う！
（このような不要なディレクトリが増えなくて済む。）

---

cssディレクトリを使うのは悪くはないんだけど、
まだcssディレクトリには一個しかファイルが配置されていないので、cssディレクトリを作るほどでもないかなと。

2024-01-06 04:12 UTC, kakeru-one commented on form_login/index.html
ディレクトリ名は、`login_form`の方が慣習的かなあ。
なんなら、`login/index.html`でもいいと思う。

2024-01-06 05:17 UTC, kawabuchi-tetsuya commented
https://github.com/ok-os-job-change-team/tetsuya-frontend-bootcamp/pull/5/commits/3b522bca17fdb31eed89adb9a681b9ad046ad341
remとpxに関して、paddingやborderなど装飾的な部分はpxが良いと思うんやけど、どう？
containerはコンテンツのサイズに関わるから、remに修正しました。
![Screenshot 2024-01-06 14 13 43](https://github.com/ok-os-job-change-team/tetsuya-frontend-bootcamp/assets/95535099/05421bdf-3891-4fad-9968-447062a2bc76)

2024-01-06 05:52 UTC, ochi-sho-private-study commented
@kawabuchi-tetsuya 

試しにブラウザのフォントサイズを40pxにしたところ、以下のような見た目になった。
以下の結果から、装飾的な部分もremにした方がフォームの見た目が崩れないのでremに統一した方が良いと思う！

## paddingやborderなど装飾的な部分もremにした場合
<details>
<summary>CSSのコードの詳細はこちら</summary>

```css
.container {
  width: 20rem;
  margin: 0 auto;
  padding: 1.25rem;
  background-color: #ffffff;
  border: 0.0625rem solid #ccc;
  border-radius: 0.3rem;
}

input[type="email"],
input[type="password"] {
  width: 93%;
  padding: 0.625rem;
  margin-bottom: 0.625rem;
  border: 0.0625rem solid #ccc;
  border-radius: 0.25rem;
}

button[type="submit"] {
  width: 100%;
  padding: 0.625rem;
  background-color: #4caf50;
  color: #ffffff;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
}
```

</details>

![スクリーンショット 2024-01-06 14 48 19](https://github.com/ok-os-job-change-team/tetsuya-frontend-bootcamp/assets/118090073/5f8b4fff-2701-49a5-ab75-fc9e660dbeff)


## paddingやborderなど装飾的な部分だけpxにした場合

![スクリーンショット 2024-01-06 14 51 10](https://github.com/ok-os-job-change-team/tetsuya-frontend-bootcamp/assets/118090073/a75bf320-c7c4-40c1-89ca-c54c034b2790)

2024-01-06 05:56 UTC, ochi-sho-private-study commented on login/style.css
IMO(In My Opinion)

このCSSファイルは今後index.htmlからしか呼ばれないと思うので、
index.htmlに合わせてindex.cssという命名の方がいいかと思う！

2024-01-06 06:05 UTC, kawabuchi-tetsuya commented on login/style.css
remに統一するのは理解した。
cssは今後作成するマイページにも使うのでは？
mypage.cssを別途作成するなら、htmlファイル内に直接書き込むのでも良かったということにならない？

2024-01-06 06:17 UTC, ochi-sho-private-study commented on login/style.css
> cssは今後作成するマイページにも使うのでは？

なるほど、共通部分があるから、マイページにも使いたいってことね？
では共通するCSSは、`common/container.css`のようなファイルを別途作成して、それぞれのhtmlファイルで読み込むようにするのはどうだろう？

## 実装例
```html
<!DOCTYPE html>
<html>
<head>
    <title>ページのタイトル</title>
    <!-- 最初のCSSファイル -->
    <link rel="stylesheet" type="text/css" href="index.css">
    <!-- 2番目のCSSファイル -->
    <link rel="stylesheet" type="text/css" href="container.css">
    <!-- その他のCSSファイルも同様に追加可能 -->
</head>
<body>
    <!-- ページのコンテンツ -->
</body>
</html>
```

2024-01-08 02:07 UTC, kawabuchi-tetsuya commented on login/style.css
https://github.com/ok-os-job-change-team/tetsuya-frontend-bootcamp/pull/5/commits/78bebadd17cba09cd4122224bcbb10810a1d0228
index.cssとcommon.cssに分割した

2024-01-08 03:32 UTC, ochi-sho-private-study approved these changes
LGTM！

2024-01-08 03:32 UTC, ochi-sho-private-study commented
![LGTM](https://i.imgur.com/hWLEk6W.jpg)

2024-01-08 04:46 UTC, merged